### ISSUE TITLE
Create a cache for zarr metadata in titiler xarray

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/titiler-xarray#22]
Instead of having titiler-xarray open_dataset on the zarr store, it should first check if the zarr metadata (.zmetadata) is stored in a cache. @sharkinsspatial suggested memcached.

**Comment by sharkinsspatial** [comment]
refs https://github.com/developmentseed/tile-benchmarking/issues/13#issue-1735382021
@abarciauskas-bgse I feel like we also had discussion in an issue somewhere about the initial zarr metadata read performance in the Lambda context but I can't seem to find where.

**Comment by abarciauskas-bgse** [comment]
@sharkinsspatial @vincentsarago here is a document to evaluate the options for caching Zarr metadata: [titiler-xarray caching metadata](https://docs.google.com/document/d/15oKzMqTqbO1JyVmuybg4pBckmkj4ePIhMwXcSxKf42k/edit)

But the TL;DR is:

### Recommendation
* It is likely that the volume of metadata files will exceed ephemeral disk storage (512MB) and even memory (up to 10GB) so we should use a persisted cache
* developmentseed/titiler already has an example of how to cache using aiocache: https://devseed.com/titiler/examples/code/tiler_with_cache/
* This method could be adapted to decorate xarray_open_dataset
* Open question: Should we try to use DynamoDB Accelerator?

## Next steps:

* Update codebase with aiocache using local redis server to verify the configuration works
* Add a redis (or memcached?) server to the CDK deployment (elasticache)
* Add the elasticache server endpoint to the environment of the application
* Assert performance improvement via tile-benchmarking e2e tests

**Comment by abarciauskas-bgse** [comment]
I've been working on adding diskcache and now I'm having trouble getting the lambda package under the allowed size. 

@sharkinsspatial @vincentsarago if you could take a look at https://github.com/developmentseed/titiler-xarray/pull/40/files and let me know if you think there are other ways to minimize package size that would be cool.

Alternatives to minimizing the current package:
1. Use fsspec for caching instead. This may be preferable anyways since according to [diskcache caveats](https://grantjenks.com/docs/diskcache/tutorial.html#caveats), diskcache may not work well with network file systems:
> SQLite is used to synchronize database access between threads and processes and as such inherits all SQLite caveats. Most notably SQLite is [not recommended](https://www.sqlite.org/faq.html#q5) for use with Network File System (NFS) mounts
2. Deploy to ECS (using Fargate)

**Comment by abarciauskas-bgse** [comment]
Update: We were able to successfully deploy the package as of commit https://github.com/developmentseed/titiler-xarray/commit/1d244ce61952a8aef5b1dc04b9857d26b125e0f9

Notes:
* At one point I was getting an error "AttributeError: 'PandasIndex' object has no attribute 'shape'" which I believe was because an xarray object was stored at one version of xarray (I think 0.19.0) and was trying to be retrieved at a different version (2023.10.0)
* Even thought the application was running successfully, it was getting an error when trying to load a map

```
[ERROR] OperationalError: disk I/O error
Traceback (most recent call last):
  File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/task/handler.py", line 7, in <module>
    from titiler.xarray.main import app
  File "/tmp/pip-target-qby4nk03/lib/python/titiler/xarray/main.py", line 9, in <module>
  File "/tmp/pip-target-qby4nk03/lib/python/titiler/xarray/reader.py", line 27, in <module>
  File "/tmp/pip-target-qby4nk03/lib/python/diskcache/core.py", line 499, in __init__
  File "/tmp/pip-target-qby4nk03/lib/python/diskcache/core.py", line 666, in _execute_with_retry
```

I wasn't too shocked by this, because as noted above, SQLite is not recommended for use with NFS mounts. I would like to fully understand the error above so we can determine if the use of Lambda + with diskcache on EFS is a total non option.

As an alternative, why don't we just use Lambda's ephermeral storage in /tmp? That can store up to 10GB of data and right now, the default setting of diskcache is only up to 1GB anyways. From what I can tell so far, most pickled xarray metadata objects will not be very large, but I'll need to do a bit more research to understand about how many datasets we could expect to store in lambda's ephemeral cache safely (without lambda crashing due to lack of space).

**Comment by abarciauskas-bgse** [comment]
A few updates on this work:
1. There is a notebook with the caching strategies summarized and reported: [caching-strategies-report.ipynb](https://github.com/developmentseed/tile-benchmarking/blob/main/03-e2e/caching-strategies-report.ipynb)
2. We are currently planning to go with fsspec's filecache + EFS but I have to figure out if we can get it working with NetCDF/HDF5 files

**Comment by abarciauskas-bgse** [comment]
I think once this is implemented we will need some way to ensure that the provisioned throughput to EFS is enough to handle load. At the moment it's configured with bursting so if somehow we use up all available burst credits, the application will start throwing an error.

**Comment by abarciauskas-bgse** [comment]
closed via https://github.com/developmentseed/titiler-xarray/pull/47
