### ISSUE TITLE
Update titiler version to 0.14 

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler-xarray#28]
The latest titiler version uses the latest rio-tiler version and the new FastAPI/Pydantic versions which should be slightly faster.

Moving from 0.11 to 0.14 might bring some breaking changes 

https://github.com/developmentseed/titiler/blob/main/CHANGES.md#0120-2023-07-17
https://github.com/developmentseed/titiler/blob/main/CHANGES.md#0130-2023-07-27
https://github.com/developmentseed/titiler/blob/main/CHANGES.md#0140-2023-08-30

**Comment by abarciauskas-bgse** [comment]
closing via #31 and #30
