### ISSUE TITLE
allow nodata override 

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler-xarray#63]
https://github.com/developmentseed/titiler-xarray/blob/940c559e811418d068a1ead5fd4274221087c264/titiler/xarray/factory.py#L247-L249

by adding https://github.com/developmentseed/titiler/blob/main/src/titiler/core/titiler/core/dependencies.py#L386-L392

cc @ciaransweet

**Comment by abarciauskas-bgse** [comment]
Ah ok thanks @vincentsarago I didn't realize we don't have that value parameterized when I wrote up #64, but I was specifically referring to the map preview UI form.

**Comment by vincentsarago** [comment]
🙏 once we add it to the tile endpoint we will do a full round `/tiles` `/tilesjon.json` ....

**Comment by ciaransweet** [comment]
So reading this am I correct in understand this would just be to add the parameter onto a frontend input and wire it in downstream?

**Comment by vincentsarago** [comment]
yes

**Comment by ciaransweet** [comment]
> yes

I might even be able to figure _that_ out!
